openapi: "3.0.3"
info:
  title: "fastFOREX.io"
  version: "1.5.1"
  description: "Foreign & cryptocurrency exchange rate API"
  termsOfService: "https://www.fastforex.io/terms-of-sale"
  contact:
    email: "support@fastforex.io"
  license:
    name: "Apache 2.0"
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"
servers:
  - url: "https://api.fastforex.io"
    description: "Production"
tags:
  - name: "currency"
    description: "Physical currencies, rates and conversions"
  - name: "crypto"
    description: "Digital currencies, pairs & prices"
  - name: "admin"
    description: "Account admin"
paths:
  /fetch-one:
    get:
      tags:
        - "currency"
        - "crypto"
      description: "Fetch a single currency exchange rate, from and to any supported physical or digital currency."
      parameters:
        - name: "from"
          in: "query"
          description: "Base currency symbol (physical or digital), defaults to USD"
          required: false
          allowEmptyValue: true
          schema:
            $ref: "#/components/schemas/AnyCurrency"
        - name: "to"
          in: "query"
          description: "Target currency symbol (physical or digital), defaults to USD"
          required: true
          schema:
            $ref: "#/components/schemas/AnyCurrency"
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                type: object
                properties:
                  base:
                    $ref: "#/components/schemas/AnyCurrency"
                  updated:
                    $ref: "#/components/schemas/DateTime"
                  ms:
                    $ref: "#/components/schemas/ResponseTime"
                  result:
                    type: object
                    minProperties: 1
                    maxProperties: 1
                    additionalProperties:
                      type: number
                      format: float
              example:
                base: USD
                result:
                  EUR: 0.82791
                updated: '2021-01-16 16:34:29'
                ms: 4
        "400":
          description: "Bad Request"
        "401":
          description: "Not Authorized"
        "403":
          description: "Forbidden"
        "429":
          description: "Rate limit exceeded"
  /fetch-multi:
    get:
      tags:
        - "currency"
      description: "Fetch multiple currency rates at once"
      parameters:
        - name: "from"
          in: "query"
          description: "Base currency 3-letter symbol, defaults to USD"
          required: false
          allowEmptyValue: true
          schema:
            $ref: "#/components/schemas/Currency"
        - name: "to"
          in: "query"
          description: "Target currencies, comma separated list of 3-letter symbols"
          required: true
          schema:
            $ref: "#/components/schemas/CurrencyList"
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                type: object
                properties:
                  base:
                    $ref: "#/components/schemas/Currency"
                  updated:
                    $ref: "#/components/schemas/DateTime"
                  ms:
                    $ref: "#/components/schemas/ResponseTime"
                  results:
                    type: object
                    minProperties: 1
                    additionalProperties:
                      type: number
                      format: float
              example:
                base: USD
                results:
                  EUR: 0.82791
                  GBP: 0.73605
                updated: '2021-01-16 16:34:29'
                ms: 8
        "400":
          description: "Bad Request"
        "401":
          description: "Not Authorized"
        "403":
          description: "Forbidden"
        "429":
          description: "Rate limit exceeded"
  /fetch-all:
    get:
      tags:
        - "currency"
      description: "Fetch all available currency rates"
      parameters:
        - name: "from"
          in: "query"
          description: "Base currency 3-letter symbol, defaults to USD"
          required: false
          allowEmptyValue: true
          schema:
            $ref: "#/components/schemas/Currency"
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                type: object
                properties:
                  base:
                    $ref: "#/components/schemas/Currency"
                  updated:
                    $ref: "#/components/schemas/DateTime"
                  ms:
                    $ref: "#/components/schemas/ResponseTime"
                  results:
                    type: object
                    minProperties: 130
                    additionalProperties:
                      type: number
                      format: float
              example:
                base: USD
                results:
                  AED: 3.67297
                  AFN: 77.11468
                  ALL: 101.78125
                  AMD: 523.67143
                  ANG: 1.78691
                  AOA: 653.45356
                  ARS: 85.74709
                  AUD: 1.29806
                  AWG: 1.79943
                  AZN: 1.70727
                  BAM: 1.62182
                  BBD: 1.99941
                  BDT: 84.84175
                  BGN: 1.61063
                  BHD: 0.37612
                  BIF: 1943.32401
                  BMD: 0.99926
                  BND: 1.32953
                  BOB: 6.88532
                  BRL: 5.29479
                  BSD: 1.00177
                  BTN: 73.22317
                  BWP: 10.98351
                  BZD: 2.01472
                  CAD: 1.27357
                  CDF: 1977.04254
                  CHF: 0.8912
                  CLF: 0.02491
                  CLP: 734.84469
                  CNH: 6.47453
                  CNY: 6.48079
                  COP: 3461.79891
                  CUP: 24.99558
                  CVE: 90.9024
                  CZK: 21.65759
                  DJF: 177.94053
                  DKK: 6.15612
                  DOP: 58.27175
                  DZD: 133.63021
                  EGP: 15.64449
                  ERN: 15.1347
                  ETB: 39.35227
                  EUR: 0.82791
                  FJD: 2.05329
                  FKP: 0.73605
                  GBP: 0.73605
                  GEL: 3.30208
                  GHS: 5.78235
                  GIP: 0.73605
                  GMD: 51.76064
                  GNF: 10080.74488
                  GTQ: 7.78301
                  GYD: 210.42985
                  HKD: 7.75357
                  HNL: 24.12042
                  HRK: 6.19682
                  HTG: 75.90461
                  HUF: 298.21139
                  IDR: 14054.17341
                  ILS: 3.2719
                  INR: 73.16164
                  IQD: 1458.41307
                  IRR: 42031.79744
                  ISK: 129.4936
                  JMD: 144.24702
                  JOD: 0.70779
                  JPY: 103.87016
                  KES: 109.70116
                  KGS: 75.50493
                  KHR: 4047.84337
                  KMF: 406.08715
                  KPW: 900.13249
                  KRW: 1102.13455
                  KWD: 0.30318
                  KYD: 0.81923
                  KZT: 418.85765
                  LAK: 9308.2585
                  LBP: 1509.38466
                  LKR: 194.62682
                  LRD: 167.93022
                  LSL: 15.21787
                  LYD: 4.45341
                  MAD: 8.91064
                  MDL: 17.18902
                  MGA: 3762.10805
                  MKD: 51.00986
                  MMK: 1331.8784
                  MNT: 2853.84955
                  MOP: 8.01634
                  MRU: 36.41764
                  MUR: 39.84837
                  MVR: 15.66392
                  MWK: 773.70087
                  MXN: 19.79604
                  MYR: 4.03732
                  MZN: 74.77698
                  NAD: 15.18769
                  NGN: 380.3327
                  NOK: 8.56904
                  NPR: 117.3193
                  NZD: 1.40232
                  OMR: 0.38422
                  PAB: 0.99926
                  PEN: 3.60165
                  PGK: 3.52819
                  PHP: 48.06492
                  PKR: 160.16046
                  PLN: 3.7535
                  PYG: 6890.343
                  QAR: 3.64022
                  RON: 4.02672
                  RSD: 96.9947
                  RUB: 73.59569
                  RWF: 972.40542
                  SAR: 3.74834
                  SCR: 21.7415
                  SDG: 55.12079
                  SEK: 8.39445
                  SGD: 1.33084
                  SHP: 0.73605
                  SLL: 10117.25305
                  SOS: 585.66171
                  SRD: 14.0817
                  SYP: 1257.58133
                  SZL: 15.23848
                  THB: 30.10158
                  TJS: 11.37737
                  TMT: 3.49448
                  TND: 2.7086
                  TOP: 2.27536
                  TRY: 7.45083
                  TTD: 6.74407
                  TWD: 28.03621
                  TZS: 2317.83454
                  UAH: 28.17938
                  UGX: 3704.99043
                  USD: 1
                  UYU: 42.4356
                  UZS: 10493.30193
                  VND: 23216.10481
                  VUV: 107.05138
                  WST: 2.54085
                  XAF: 542.97807
                  XCD: 2.69954
                  XDR: 0.69699
                  XOF: 542.97807
                  XPF: 98.70455
                  YER: 246.27558
                  ZAR: 15.20595
                  ZMW: 21.37472
                updated: '2021-01-16 17:14:51'
                ms: 13
        "400":
          description: "Bad Request"
        "401":
          description: "Not Authorized"
        "403":
          description: "Forbidden"
        "429":
          description: "Rate limit exceeded"
  /convert:
    get:
      tags:
        - "currency"
        - "crypto"
      description: "Convert an amount of one currency into another currency (supports physical and digital currencies)"
      parameters:
        - name: "from"
          in: "query"
          description: "Base currency symbol (physical or digital)"
          required: false
          allowEmptyValue: true
          schema:
            $ref: "#/components/schemas/AnyCurrency"
        - name: "to"
          in: "query"
          description: "Target currency symbol (physical or digital)"
          required: true
          schema:
            $ref: "#/components/schemas/AnyCurrency"
        - name: "amount"
          in: "query"
          description: "Amount of source currency to convert"
          required: true
          schema:
            type: number
            format: float
            minimum: 0.01
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                type: object
                properties:
                  base:
                    $ref: "#/components/schemas/AnyCurrency"
                  ms:
                    $ref: "#/components/schemas/ResponseTime"
                  amount:
                    type: number
                    format: float
                  result:
                    type: object
                    minProperties: 2
                    maxProperties: 2
                    properties:
                      rate:
                        type: number
                        format: float
                    additionalProperties:
                      type: number
                      format: float
              example:
                base: USD
                amount: 199.5
                result:
                  EUR: 164.29
                  rate: 0.82353
                ms: 7
        "400":
          description: "Bad Request"
        "401":
          description: "Not Authorized"
        "403":
          description: "Forbidden"
        "429":
          description: "Rate limit exceeded"
  /historical:
    get:
      tags:
        - "currency"
      description: "Fetch exchange rates for a date in the past"
      parameters:
        - name: "date"
          in: "query"
          description: "UTC date in YYYY-MM-DD format. Must be in the past and after 2015-01-01."
          required: true
          schema:
            $ref: "#/components/schemas/Date"
        - name: "from"
          in: "query"
          description: "Base currency 3-letter symbol, defaults to USD"
          required: false
          allowEmptyValue: true
          schema:
            $ref: "#/components/schemas/Currency"
        - name: "to"
          in: "query"
          description: "Target currencies, comma separated list of 3-letter symbols. Defaults to all currencies if omitted"
          required: false
          allowEmptyValue: true
          schema:
            $ref: "#/components/schemas/CurrencyList"
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                type: object
                properties:
                  base:
                    $ref: "#/components/schemas/Currency"
                  date:
                    $ref: "#/components/schemas/Date"
                  ms:
                    $ref: "#/components/schemas/ResponseTime"
                  results:
                    type: object
                    minProperties: 130
                    additionalProperties:
                      type: number
                      format: float
              example:
                date: '2021-01-16'
                base: USD
                results:
                  AED: 3.67297
                  AFN: 77.11468
                  ALL: 101.78125
                  AMD: 523.67143
                  ANG: 1.78691
                  AOA: 653.45356
                  ARS: 85.74709
                  AUD: 1.29806
                  AWG: 1.79943
                  AZN: 1.70727
                  BAM: 1.62182
                  BBD: 1.99941
                  BDT: 84.84175
                  BGN: 1.61063
                  BHD: 0.37612
                  BIF: 1943.32401
                  BMD: 0.99926
                  BND: 1.32953
                  BOB: 6.88532
                  BRL: 5.29479
                  BSD: 1.00177
                  BTN: 73.22317
                  BWP: 10.98351
                  BZD: 2.01472
                  CAD: 1.27357
                  CDF: 1977.04254
                  CHF: 0.8912
                  CLF: 0.02491
                  CLP: 734.84469
                  CNH: 6.47453
                  CNY: 6.48079
                  COP: 3461.79891
                  CUP: 24.99558
                  CVE: 90.9024
                  CZK: 21.65759
                  DJF: 177.94053
                  DKK: 6.15612
                  DOP: 58.27175
                  DZD: 133.63021
                  EGP: 15.64449
                  ERN: 15.1347
                  ETB: 39.35227
                  EUR: 0.82791
                  FJD: 2.05329
                  FKP: 0.73605
                  GBP: 0.73605
                  GEL: 3.30208
                  GHS: 5.78235
                  GIP: 0.73605
                  GMD: 51.76064
                  GNF: 10080.74488
                  GTQ: 7.78301
                  GYD: 210.42985
                  HKD: 7.75357
                  HNL: 24.12042
                  HRK: 6.19682
                  HTG: 75.90461
                  HUF: 298.21139
                  IDR: 14054.17341
                  ILS: 3.2719
                  INR: 73.16164
                  IQD: 1458.41307
                  IRR: 42031.79744
                  ISK: 129.4936
                  JMD: 144.24702
                  JOD: 0.70779
                  JPY: 103.87016
                  KES: 109.70116
                  KGS: 75.50493
                  KHR: 4047.84337
                  KMF: 406.08715
                  KPW: 900.13249
                  KRW: 1102.13455
                  KWD: 0.30318
                  KYD: 0.81923
                  KZT: 418.85765
                  LAK: 9308.2585
                  LBP: 1509.38466
                  LKR: 194.62682
                  LRD: 167.93022
                  LSL: 15.21787
                  LYD: 4.45341
                  MAD: 8.91064
                  MDL: 17.18902
                  MGA: 3762.10805
                  MKD: 51.00986
                  MMK: 1331.8784
                  MNT: 2853.84955
                  MOP: 8.01634
                  MRU: 36.41764
                  MUR: 39.84837
                  MVR: 15.66392
                  MWK: 773.70087
                  MXN: 19.79604
                  MYR: 4.03732
                  MZN: 74.77698
                  NAD: 15.18769
                  NGN: 380.3327
                  NOK: 8.56904
                  NPR: 117.3193
                  NZD: 1.40232
                  OMR: 0.38422
                  PAB: 0.99926
                  PEN: 3.60165
                  PGK: 3.52819
                  PHP: 48.06492
                  PKR: 160.16046
                  PLN: 3.7535
                  PYG: 6890.343
                  QAR: 3.64022
                  RON: 4.02672
                  RSD: 96.9947
                  RUB: 73.59569
                  RWF: 972.40542
                  SAR: 3.74834
                  SCR: 21.7415
                  SDG: 55.12079
                  SEK: 8.39445
                  SGD: 1.33084
                  SHP: 0.73605
                  SLL: 10117.25305
                  SOS: 585.66171
                  SRD: 14.0817
                  SYP: 1257.58133
                  SZL: 15.23848
                  THB: 30.10158
                  TJS: 11.37737
                  TMT: 3.49448
                  TND: 2.7086
                  TOP: 2.27536
                  TRY: 7.45083
                  TTD: 6.74407
                  TWD: 28.03621
                  TZS: 2317.83454
                  UAH: 28.17938
                  UGX: 3704.99043
                  USD: 1
                  UYU: 42.4356
                  UZS: 10493.30193
                  VND: 23216.10481
                  VUV: 107.05138
                  WST: 2.54085
                  XAF: 542.97807
                  XCD: 2.69954
                  XDR: 0.69699
                  XOF: 542.97807
                  XPF: 98.70455
                  YER: 246.27558
                  ZAR: 15.20595
                  ZMW: 21.37472
                ms: 13
        "400":
          description: "Bad Request"
        "401":
          description: "Not Authorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found - We do not have historical rates for the requested date and currency pair"
        "429":
          description: "Rate limit exceeded"
  /time-series:
    get:
      tags:
        - "currency"
      description: "Fetch a time-series dataset of currency rates for the specified interval (only daily supported at launch)"
      parameters:
        - name: "from"
          in: "query"
          description: "Base currency 3-letter symbol, defaults to USD"
          required: false
          allowEmptyValue: true
          schema:
            $ref: "#/components/schemas/Currency"
        - name: "to"
          in: "query"
          description: "Target currency 3-letter symbol"
          required: true
          schema:
            $ref: "#/components/schemas/Currency"
        - name: "start"
          in: "query"
          description: "UTC start date in YYYY-MM-DD format. Must be in the past and after 2015-01-01."
          required: true
          schema:
            $ref: "#/components/schemas/Date"
        - name: "end"
          in: "query"
          description: "UTC end date in YYYY-MM-DD format. Must be in the past and after 2015-01-01."
          required: true
          schema:
            $ref: "#/components/schemas/Date"
        - name: "interval"
          in: "query"
          description: "ISO8601 duration, such as P1D (daily). Defaults to P1D. At launch only supports daily."
          required: false
          schema:
            $ref: "#/components/schemas/Duration"
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                type: object
                properties:
                  start:
                    $ref: "#/components/schemas/Date"
                  end:
                    $ref: "#/components/schemas/Date"
                  interval:
                    $ref: "#/components/schemas/Duration"
                  base:
                    $ref: "#/components/schemas/Currency"
                  ms:
                    $ref: "#/components/schemas/ResponseTime"
                  results:
                    type: object
                    minProperties: 1
                    additionalProperties:
                      type: number
                      format: float
              example:
                start: '2021-01-24'
                end: '2021-01-30'
                interval: 'P1D'
                base: USD
                results:
                  GBP:
                    '2021-01-24': 1.14
                    '2021-01-25': 1.14
                    '2021-01-26': 1.15
                    '2021-01-27': 1.16
                    '2021-01-28': 1.14
                    '2021-01-29': 1.13
                    '2021-01-30': 1.14
        "400":
          description: "Bad Request"
        "401":
          description: "Not Authorized"
        "403":
          description: "Forbidden"
        "429":
          description: "Rate limit exceeded"
  /currencies:
    get:
      tags:
        - "currency"
      description: "Fetch a list of supported currencies"
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                type: object
                properties:
                  ms:
                    $ref: "#/components/schemas/ResponseTime"
                  currencies:
                    type: object
                    minProperties: 130
                    additionalProperties:
                      type: string
              example:
                currencies:
                  AED: United Arab Emirates Dirham
                  AFN: Afghan Afghani
                  ALL: Albanian Lek
                  AMD: Armenian Dram
                  ANG: Dutch Guilders
                  AOA: Angolan Kwanza
                  ARS: Argentine Peso
                  AUD: Australian Dollar
                  AWG: Aruban Florin
                  AZN: Azerbaijani Manat
                  BAM: Bosnia-Herzegovina Convertible Mark
                  BBD: Barbadian Dollar
                  BDT: Bangladeshi Taka
                  BGN: Bulgarian Lev
                  BHD: Bahraini Dinar
                  BIF: Burundian Franc
                  BMD: Bermudian Dollar
                  BND: Bruneian Dollar
                  BOB: Bolivian Boliviano
                  BRL: Brazilian Real
                  BSD: Bahamian Dollar
                  BTN: Bhutanese Ngultrum
                  BWP: Botswanan Pula
                  BZD: Belizean Dollar
                  CAD: Canadian Dollar
                  CDF: Congolese Franc
                  CHF: Swiss Franc
                  CLF: Chilean Unit of Account UF
                  CLP: Chilean Peso
                  CNH: Chinese Yuan Offshore
                  CNY: Chinese Yuan
                  COP: Colombian Peso
                  CUP: Cuban Peso
                  CVE: Cape Verdean Escudo
                  CZK: Czech Republic Koruna
                  DJF: Djiboutian Franc
                  DKK: Danish Krone
                  DOP: Dominican Peso
                  DZD: Algerian Dinar
                  EGP: Egyptian Pound
                  ERN: Eritrean Nakfa
                  ETB: Ethiopian Birr
                  EUR: Euro
                  FJD: Fijian Dollar
                  FKP: Falkland Islands Pound
                  GBP: British Pound Sterling
                  GEL: Georgian Lari
                  GHS: Ghanaian Cedi
                  GIP: Gibraltar Pound
                  GMD: Gambian Dalasi
                  GNF: Guinean Franc
                  GTQ: Guatemalan Quetzal
                  GYD: Guyanaese Dollar
                  HKD: Hong Kong Dollar
                  HNL: Honduran Lempira
                  HRK: Croatian Kuna
                  HTG: Haitian Gourde
                  HUF: Hungarian Forint
                  IDR: Indonesian Rupiah
                  ILS: Israeli New Sheqel
                  INR: Indian Rupee
                  IQD: Iraqi Dinar
                  IRR: Iranian Rial
                  ISK: Icelandic Krona
                  JMD: Jamaican Dollar
                  JOD: Jordanian Dinar
                  JPY: Japanese Yen
                  KES: Kenyan Shilling
                  KGS: Kyrgystani Som
                  KHR: Cambodian Riel
                  KMF: Comorian Franc
                  KPW: North Korean Won
                  KRW: South Korean Won
                  KWD: Kuwaiti Dinar
                  KYD: Caymanian Dollar
                  KZT: Kazakhstani Tenge
                  LAK: Laotian Kip
                  LBP: Lebanese Pound
                  LKR: Sri Lankan Rupee
                  LRD: Liberian Dollar
                  LSL: Basotho Maloti
                  LYD: Libyan Dinar
                  MAD: Moroccan Dirham
                  MDL: Moldovan Leu
                  MGA: Malagasy Ariary
                  MKD: Macedonian Denar
                  MMK: Myanma Kyat
                  MNT: Mongolian Tugrik
                  MOP: Macanese Pataca
                  MRU: Mauritanian Ouguiya
                  MUR: Mauritian Rupee
                  MVR: Maldivian Rufiyaa
                  MWK: Malawian Kwacha
                  MXN: Mexican Peso
                  MYR: Malaysian Ringgit
                  MZN: Mozambican Metical
                  NAD: Namibian Dollar
                  NGN: Nigerian Naira
                  NOK: Norwegian Krone
                  NPR: Nepalese Rupee
                  NZD: New Zealand Dollar
                  OMR: Omani Rial
                  PAB: Panamanian Balboa
                  PEN: Peruvian Nuevo Sol
                  PGK: Papua New Guinean Kina
                  PHP: Philippine Peso
                  PKR: Pakistani Rupee
                  PLN: Polish Zloty
                  PYG: Paraguayan Guarani
                  QAR: Qatari Rial
                  RON: Romanian Leu
                  RSD: Serbian Dinar
                  RUB: Russian Ruble
                  RWF: Rwandan Franc
                  SAR: Saudi Arabian Riyal
                  SCR: Seychellois Rupee
                  SDG: Sudanese Pound
                  SEK: Swedish Krona
                  SGD: Singapore Dollar
                  SHP: Saint Helena Pound
                  SLL: Sierra Leonean Leone
                  SOS: Somali Shilling
                  SRD: Surinamese Dollar
                  SYP: Syrian Pound
                  SZL: Swazi Emalangeni
                  THB: Thai Baht
                  TJS: Tajikistani Somoni
                  TMT: Turkmenistani Manat
                  TND: Tunisian Dinar
                  TOP: Tongan Pa'anga
                  TRY: Turkish Lira
                  TTD: Trinidad and Tobago Dollar
                  TWD: Taiwan New Dollar
                  TZS: Tanzanian Shilling
                  UAH: Ukrainian Hryvnia
                  UGX: Ugandan Shilling
                  USD: United States Dollar
                  UYU: Uruguayan Peso
                  UZS: Uzbekistan Som
                  VND: Vietnamese Dong
                  VUV: Ni-Vanuatu Vatu
                  WST: Samoan Tala
                  XAF: CFA Franc BEAC
                  XCD: East Caribbean Dollar
                  XDR: Special Drawing Rights
                  XOF: CFA Franc BCEAO
                  XPF: CFP Franc
                  YER: Yemeni Rial
                  ZAR: South African Rand
                  ZMW: Zambian Kwacha
                ms: 8
        "400":
          description: "Bad Request"
        "401":
          description: "Not Authorized"
        "429":
          description: "Rate limit exceeded"
  /crypto/currencies:
    get:
      tags:
        - "crypto"
      description: "Fetch a list of 200+ supported cryptocurrencies"
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                type: object
                properties:
                  ms:
                    $ref: "#/components/schemas/ResponseTime"
                  currencies:
                    type: object
                    minProperties: 200
                    additionalProperties:
                      type: string
              example:
                currencies:
                  1INCH: 1inch Network
                  AAVE: Aave
                  ACA: Acala Token
                  ACH: Alchemy Pay
                  ADA: Cardano
                  AERGO: Aergo
                ms: 8
        "400":
          description: "Bad Request"
        "401":
          description: "Not Authorized"
        "429":
          description: "Rate limit exceeded"
  /crypto/pairs:
    get:
      tags:
        - "crypto"
      description: "Fetch a list of 400+ supported cryptocurrency pairs"
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                type: object
                properties:
                  ms:
                    $ref: "#/components/schemas/ResponseTime"
                  pairs:
                    type: object
                    minProperties: 400
                    additionalProperties:
                      $ref: "#/components/schemas/AnyCurrencyPair"
              example:
                pairs:
                  1INCH/BTC:
                    base: 1INCH
                    quote: BTC
                  BTC/USD:
                    base: BTC
                    quote: USD
                  ETH/BTC:
                    base: ETH
                    quote: BTC
                ms: 8
        "400":
          description: "Bad Request"
        "401":
          description: "Not Authorized"
        "429":
          description: "Rate limit exceeded"
  /crypto/fetch-prices:
    get:
      tags:
        - "crypto"
      description: "Fetch one or more (up to 10) real-time prices for supported cryptocurrency pairs"
      parameters:
        - name: "pairs"
          in: "query"
          description: "Up to 10 target currency pairs, comma separated in XXX/YYY format"
          required: true
          schema:
            $ref: "#/components/schemas/CryptoCurrencyPairList"
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                type: object
                properties:
                  ms:
                    $ref: "#/components/schemas/ResponseTime"
                  prices:
                    type: object
                    minProperties: 1
                    additionalProperties:
                      type: number
                      format: float
              example:
                prices:
                  BTC/USD: 20624.21
                  ETH/BTC: 0.075316
                ms: 8
        "400":
          description: "Bad Request"
        "401":
          description: "Not Authorized"
        "403":
          description: "Forbidden"
        "429":
          description: "Rate limit exceeded"
  /usage:
    get:
      tags:
        - "admin"
      description: "Fetch recent usage data for the supplied API key. Includes current period start, end, usage and quota remaining"
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                type: object
                properties:
                  monthly_quota:
                    type: number
                    format: int32
                  ms:
                    $ref: "#/components/schemas/ResponseTime"
                  usage:
                    type: object
                    minProperties: 15
                    maxProperties: 15
                    additionalProperties:
                      type: number
                      format: int32
                  current_period:
                    type: object
                    properties:
                      start:
                        $ref: "#/components/schemas/Date"
                      end:
                        $ref: "#/components/schemas/Date"
                      remaining_quota:
                        type: number
                        format: int32
                      usage:
                        type: number
                        format: int32
              example:
                usage:
                  '2021-01-24': 247
                  '2021-01-25': 312
                  '2021-01-26': 23
                  '2021-01-27': 159
                  '2021-01-28': 0
                  '2021-01-29': 45
                  '2021-01-30': 92
                  '2021-01-31': 240
                  '2021-02-01': 1204
                  '2021-02-02': 34
                  '2021-02-03': 1245
                  '2021-02-04': 4
                  '2021-02-05': 0
                  '2021-02-06': 53
                  '2021-02-07': 3245
                monthly_quota: 500000
                current_period:
                  'start': '2021-02-03'
                  'end': '2021-03-02'
                  'remaining_quota': 495453
                  'usage': 4547
                ms: 3
        "401":
          description: "Not Authorized"
        "429":
          description: "Rate limit exceeded"
security:
  - api_key: []
components:
  schemas:
    Currency:
      type: "string"
      pattern: "[A-Z]{3}"
      description: "Three-letter ISO 4217 currency code"
    CurrencyList:
      type: "string"
      pattern: "[A-Z]{3}(,[A-Z]{3})*"
      description: "A comma-separated list of three-letter ISO 4217 currency codes"
    AnyCurrency:
      type: "string"
      pattern: "[A-Z0-9]{3,6}"
      description: "Currency code for a physical or digital/cryptocurrency"
    CryptoCurrencyPairList:
      type: "string"
      pattern: "[A-Z0-9]{3,6}/[A-Z0-9]{3,6}(,[A-Z0-9]{3,6}/[A-Z0-9]{3,6})*"
      description: "A comma-separated list of crypto pairs"
    AnyCurrencyPair:
      type: object
      description: "Defines a currency trading pair."
      properties:
        base:
          type: string
          pattern: "[A-Z0-9]{3,6}"
          description: "Base currency in the pair"
        quote:
          type: string
          pattern: "[A-Z0-9]{3,6}"
          description: "Quote currency in the pair"
      example:
        base: USD
        quote: BTC
    ResponseTime:
      type: number
      format: int32
      description: "Server response time in milliseconds"
    DateTime:
      type: string
      pattern: "[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}"
      description: "UTC/GMT datetime YYYY-MM-DD HH:MM:SS"
    Date:
      type: string
      pattern: "[0-9]{4}-[0-9]{2}-[0-9]{2}"
      description: "UTC/GMT date YYYY-MM-DD"
    Duration:
      type: string
      description: "ISO8601 Duration. https://en.wikipedia.org/wiki/ISO_8601#Durations"
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: query
externalDocs:
  description: "Find out more about fastFOREX.io"
  url: "https://www.fastforex.io"
x-samples-languages:
  - curl
  - node
  - ruby
  - javascript
  - python
  - php
  - go
  - java
  - swift
x-proxy-enabled: false
